name: release
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish portable EXE
        run: >
          dotnet publish src/BloodysManager.App/BloodysManager.App.csproj
          -c Release -r win-x64
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -p:PublishReadyToRun=true
          --self-contained true
          -o publish/win-x64
      - uses: actions/upload-artifact@v4
        with:
          name: BloodysManager-win-x64
          path: publish/win-x64/**
